//package exceptionHandling;
//
//public class ArithematicDemo {
//    public static void main(String[] args) {
//        private void checkExpetion(){
//            try
//            {
//                int a=0;
//                int result =10/a;
//                System.out.println();
//            }
//            catch (exception e)
//            {
//
//            }
//        }
//    }
//}
